### ISSUE TITLE
sh scripts/build_wasm_thread.sh 

### ISSUE THREAD

**Issue by kevinchen1223** [xiyuyizhi/ffmpeg_api_use_demo#1]
error: implicit declaration of function 'av_file_map' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  result = av_file_map(argv[1], &buffer, &buffer_size, 0, NULL);

error: implicit declaration of function 'av_file_unmap' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  av_file_unmap(buffer, buffer_size);

**Comment by xiyuyizhi** [comment]
可以先pull 下代码

编译wasm版本时先注释掉 base.h中  #define MAIN_RUN
